# Generated by Django 3.2.15 on 2022-08-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
