# Generated by Django 3.2.15 on 2022-08-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(null=True, unique=True),
        ),
    ]
