# Generated by Django 3.2.15 on 2022-08-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220811_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_name_user',
            field=models.TextField(null=True, unique=True),
        ),
    ]
