# Generated by Django 3.2.15 on 2022-08-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comment',
            field=models.ManyToManyField(blank=True, to='post.comment'),
        ),
    ]
