# Generated by Django 3.2.15 on 2022-08-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_posts_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comment',
            field=models.ManyToManyField(to='post.comment'),
        ),
    ]
