# Generated by Django 3.2.15 on 2022-08-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_posts_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='ofpost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.posts'),
            preserve_default=False,
        ),
    ]
